dirs:
    exp: aishell
    train:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/train.trans
        align: /home/user/easton/data/AISHELL/kaldi_gen/train.phone.frame
        wav_scp: /home/user/easton/data/AISHELL/kaldi_gen/train_wav.scp
        tfdata: /home/user/easton/data/AISHELL/tfdata/train_feats_13_5_2_3
    train_supervise:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/train6000.trans
        align: /home/user/easton/data/AISHELL/kaldi_gen/train6000.phone.frame
        wav_scp: /home/user/easton/data/AISHELL/kaldi_gen/train6000_wav.scp
        tfdata: /home/user/easton/data/AISHELL/tfdata/train6000_feats_13_5_2_3
    dev:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/dev.trans
        align: /home/user/easton/data/AISHELL/kaldi_gen/dev.phone.frame
        wav_scp: /home/user/easton/data/AISHELL/kaldi_gen/dev_wav.scp
        tfdata: /home/user/easton/data/AISHELL/tfdata/dev_feats_13_5_2_3
    test:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/test.trans
    lm:
        data: /home/user/easton/data/AISHELL/kaldi_gen/train.txt
    type: csv
    vocab: /home/user/easton/data/AISHELL/kaldi_gen/phones217.vocab
    # checkpoint:

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: phone

model:
    G:
        structure: fc
        num_hidden: 512
        num_layers: 1
    D:
        num_hidden: 512
        num_blocks: 5

opti:
    type: adam
    D_G_rate: 1
    G:
        lr: 0.0005
    D:
        lr: 0.0005

dev_step: 50
decode_step: 50
save_step: 50

gpus: '0'
# gpus: '1,2,3'
batch_size: 250
num_batch_tokens: 80000
bucket_boundaries: 238,300,372,437,800
num_epochs: 100000
num_steps: 500000
max_seq_len: 300
seed: 0

lambda_fs: 0.001
lambda_gp: 10.0
