dirs:
    exp: aishell
    train:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/train.trans
        align: /home/user/easton/data/AISHELL/kaldi_gen/train.phone.frame
        wav_scp: /home/user/easton/data/AISHELL/kaldi_gen/train_wav.scp
        tfdata: /home/user/easton/data/AISHELL/tfdata/train_feats_13_5_2_3
    train_supervise:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/train6000.trans
        align: /home/user/easton/data/AISHELL/kaldi_gen/train6000.phone.frame
        wav_scp: /home/user/easton/data/AISHELL/kaldi_gen/train6000_wav.scp
        tfdata: /home/user/easton/data/AISHELL/tfdata/train6000_feats_13_5_2_3
    dev:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/dev.trans
        align: /home/user/easton/data/AISHELL/kaldi_gen/dev.phone.frame
        wav_scp: /home/user/easton/data/AISHELL/kaldi_gen/dev_wav.scp
        tfdata: /home/user/easton/data/AISHELL/tfdata/dev_feats_13_5_2_3
    test:
        trans: /home/user/easton/data/AISHELL/kaldi_gen/test.trans
    type: csv
    vocab: /home/user/easton/data/AISHELL/kaldi_gen/phones217+1.vocab
    checkpoint: /home/user/easton/projects/EODM/exps/aishell/aishell_CTC2/bGRU_217/checkpoint

data:
    featType: mfcc
    dim_raw_input: 13
    left_context: 5
    right_context: 5
    downsample: 2
    add_delta: True
    unit: phone

model:
    G:
        # structure: fc
        # num_hidden: 512
        # num_layers: 1
        structure: bGRU
        num_hidden: 256
        num_layers: 2
        # dropout: 0.5

opti:
    type: adam
    lr: 0.0004

dev_step: 200
decode_step: 200
save_step: 200

gpus: '0'
batch_size: 30
num_supervised:
num_batch_tokens: 15000
bucket_boundaries: 161,182,202,223,245,269,297,334,423,726,1000
seed: 8
lambda_fs: 0.0001
