dirs:
    train:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/train-clean-100.phone.random.csv
        tfdata: /data/sxu/easton/data/libriSpeech/libri_phone/tfdata/train
    dev:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/dev1000.phone.csv
        tfdata: /data/sxu/easton/data/libriSpeech/libri_phone/tfdata/dev
    test:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/dev1000.phone.csv
    type: csv
    vocab: /data/sxu/easton/data/libriSpeech/libri_phone/phones_42.txt
    ngram: /data/sxu/easton/data/libriSpeech/libri_phone/100h.5gram

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone
    ngram: 5
    top_k: 1000
    k: 1000

model:
    G:
        structure: fc
        num_hidden: 512
        num_layers: 1

opti:
    type: adam
    peak: 0.0004

dev_step: 200
decode_step: 200
save_step: 200

gpus: '0'
# gpus: '1,2,3'
batch_size: 550
num_batch_tokens: 80000
bucket_boundaries: 238,300,372,437,800
num_epochs: 100000
num_steps: 500000
max_seq_len: 300
num_supervised: 250
seed: 8

lambda_fs: 0.00005
lambda_gp: 10.0
