dirs:
    train:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/train-clean-100.phone.random.csv
        tfdata: /data/sxu/easton/data/libriSpeech/libri_phone/tfdata/train
    dev:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/dev1000.phone.csv
        tfdata: /data/sxu/easton/data/libriSpeech/libri_phone/tfdata/dev
    test:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/dev1000.phone.csv
    lm:
        data: /data/sxu/easton/data/libriSpeech/libri_phone/train-clean-100.txt
    type: csv
    vocab: /data/sxu/easton/data/libriSpeech/libri_phone/phones_42.txt

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 2
    add_delta: True
    unit: phone

model:
    G:
        structure: fc
        num_hidden: 512
        num_layers: 2
    D:
        num_hidden: 512
        num_blocks: 5
        max_label_len: 60

opti:
    type: adam
    D_G_rate: 1
    G:
        lr: 0.0005
    D:
        lr: 0.0005

dev_step: 50
decode_step: 50
save_step: 50

gpus: '0'
# gpus: '1,2,3'
batch_size: 150
num_batch_tokens: 80000
bucket_boundaries: 238,300,372,437,800
num_epochs: 100000
num_steps: 500000
max_seq_len: 300
seed: 8

lambda_fs: 0.00005
lambda_gp: 10.0
