dirs:
    train:
        wav_scp: /data/sxu/easton/data/TIMIT/train_wav.scp
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/train_feats
    dev:
        wav_scp: /data/sxu/easton/data/TIMIT/test_wav.scp
        align: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/exp/tri3_test_ali/test.phone.frame
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/test_feats
    test:
        trans: /data/sxu/easton/projects/kaldi-2019/egs/timit/try1/data/test/text
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.vocab
    checkpoint: /data/sxu/easton/projects/EODM/exps/timit_AE/try2/checkpoint

data:
    featType: mfcc
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: phone

model:
    num_hidden_fc: 64
    num_hidden_rnn: 32
    dropout: 0.3

opti:
    lr: 0.0004

dev_step: 200
save_step: 200

gpus: '0'
batch_size: 500
