dirs:
    exp: timit
    train:
        trans: /home/user/easton/data/TIMIT/kaldi_gen/train.trans
        wav_scp: /home/user/easton/data/TIMIT/kaldi_gen/train_wav.scp
        tfdata: /home/user/easton/data/TIMIT/tfdata/train_feats_13_2_3_3
    train_supervise:
        trans: /home/user/easton/data/TIMIT/kaldi_gen/train_200.trans
        wav_scp: /home/user/easton/data/TIMIT/kaldi_gen/train200_wav.scp
        tfdata: /home/user/easton/data/TIMIT/tfdata/train200_feats_13_2_3_3
    dev:
        trans: /home/user/easton/data/TIMIT/kaldi_gen/test.trans
        wav_scp: /home/user/easton/data/TIMIT/kaldi_gen/test_wav.scp
        tfdata: /home/user/easton/data/TIMIT/tfdata/test_feats_13_2_3_3
    test:
        trans: /home/user/easton/data/TIMIT/kaldi_gen/test.trans
    type: csv
    vocab: /home/user/easton/data/TIMIT/phone39.vocab
    # checkpoint: /home/user/easton/projects/EODM/exps/timit_supervised/supervise_200_split_bGRU/checkpoint
    # checkpoint: /home/user/easton/projects/EODM/exps/timit_supervised/supervise_split_bGRU.align/checkpoint

data:
    featType: mfcc
    dim_raw_input: 13
    left_context: 0
    right_context: 2
    downsample: 3
    add_delta: True
    unit: phone

model:
    attention:
        structure: GRU
        # structure: conv
        filter_size: 3
        num_layers: 2
        num_hidden: 256
        dropout: 0.2
        threshold: 0.95
    G:
        structure: GRU
        num_hidden: 256
        dropout: 0.2
        num_layers: 1
opti:
    D_G_rate: 1
    G:
        lr: 0.0002
    D:
        lr: 0.0002

dev_step: 100
decode_step: 100
save_step: 100

gpus: '0'
batch_size: 400
# batch_size: 5
max_label_len: 60
num_supervised:

lambda_gp: 10.0
lambda_supervision: 5.0
